---

- hosts: localhost  
  handlers:
    - name: Restart apache
      become: true
      service:
        name: apache2
        state:  restarted
      listen: "restart apache"

  tasks:
    - name: Create config
      file:
        path: /temp/dir1
        state: directory
      notify: "restart apache "

    - name: Create config
      file:
        path: /temp/dir3
        state: directory