---

- hosts: localhost  
  handlers:
    - name: Restart apache
      became: true
      service:
        name: apache2
        state:  restarted
      listen: "restart apache"

  tasks:
    - name: Create config
      file:
        path: /temp/dir1
      notify: "restart apache "