---

- hosts: localhost  
  handlers:
    - name: Restart apache
      become: true
      service:
        name: apache2
        state:  restarted
      listen: "restart apache"

  tasks:
    - name: Create config
      file:
        path: /tmp/dir1
        state: directory
      notify: "restart apache "

    - name: Create config
      file:
        path: /tmp/dir3
        state: directory

    - name: With loops
      file:
        path: /tmp/example/{{ item }}
        state:  touch
      with_items: 
        - testfile1
        - testfile2
        - testfile3