---

- hosts: localhost  
  tasks:
    - name: Create file
      become: true
      file:
        path: /tmp/testfile
        state: touch
      register: output


    - debug:
        msg:  "Debug message is {{ output }}"
