---

- hosts: localhost  
  tasks:
    - name: Install apache
      become: true
      apt:
        name: apache2
        state: latest

    -name: Start apache
      become: true
      services:
        name: apache2
        state:  started
    